app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_add_user:
    defaults: { _controller: "AppBundle:Admin:addUser" }
    path: /add

admin_user_list:
    defaults: { _controller: "AppBundle:Admin:userList" }
    path: /user-list
    
admin_promote_user:
    defaults: { _controller: "AppBundle:Admin:promoteUser", id: 0 ,role: "ROLE_USER" }
    path: /promote-user/{id}/{role}/

admin_edit_user:
    defaults: { _controller: "AppBundle:Admin:editUser" }
    path: /edit-user
    
admin_demote_user:
    defaults: { _controller: "AppBundle:Admin:demoteUser",  id: 0 ,role: "ROLE_USER" }
    path: /demote-user/{id}/{role}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app_registration:
    defaults: { _controller: "AppBundle:Registration:register" }
    path: /register/

avanzu_admin_profile:
    defaults: { _controller: "AppBundle:Security:show" }
    path: /profile

avanzu_admin_logout:
    defaults: { _controller: "FOSUserBundle:Security:logout" }
    path: /logout

app_list_document:
    defaults: { _controller: "AppBundle:Default:listDocument" }
    path: /list-document

app_edit_document:
    defaults: { _controller: "AppBundle:Default:editDocument", id: 0 }
    path: /edit-document/{id}

app_add_document:
    defaults: { _controller: "AppBundle:Default:addDocument" }
    path: /add-document

app_delete_document:
    defaults: { _controller: "AppBundle:Default:deleteDocument" }
    path: /delete-document

app_active_document:
    defaults: { _controller: "AppBundle:Default:activeDocument" }
    path: /active-document

# intalniri

app_list_meeting:
    defaults: { _controller: "AppBundle:Meeting:listMeetings" }
    path: /list-meetings

app_edit_meeting:
    defaults: { _controller: "AppBundle:Meeting:editMeeting", id: 0 }
    path: /edit-meeting/{id}

app_add_meeting:
    defaults: { _controller: "AppBundle:Meeting:addMeeting" }
    path: /add-meeting

app_delete_meeting:
    defaults: { _controller: "AppBundle:Meeting:deleteMeeting" }
    path: /delete-meeting

app_active_meeting:
    defaults: { _controller: "AppBundle:Meeting:activeMeeting" }
    path: /active-meeting

app_list_document_student:
    defaults: { _controller: "AppBundle:Default:listDocumentsForStudent" }
    path: /list-document-student

app_add_document_student:
    defaults: { _controller: "AppBundle:Default:addDocumentStudent" }
    path: /add-document-student